---

- name: download ninja
  become: yes
  unarchive:
    src: https://github.com/ninja-build/ninja/releases/download/v{{ ninja_version }}/ninja-linux.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
  tags:
    - ninja
