---

- name: create temporary directory
  tempfile:
    state: directory
  register: temp
  tags:
    - ghq

- name: download
  unarchive:
    src: "https://github.com/motemen/ghq/releases/download/v{{ ghq_version }}/ghq_linux_amd64.zip"
    dest: "{{ temp.path }}"
    remote_src: yes
  tags:
    - ghq

- name: copy
  become: yes
  copy:
    src: "{{ temp.path }}/ghq"
    dest: /usr/local/bin
    mode: +x
    remote_src: yes
  tags:
    - ghq

- name: remove temporary directory
  file:
    path: "{{ temp.path }}"
    state: absent
  tags:
    - ghq
