---

- name: install bash-completion
  become: yes
  apt:
    name: bash-completion
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - dotfiles

- name: install dotfiles
  shell: curl -L http://bit.ly/rinatz-dotfiles | bash
  args:
    warn: no
  tags:
    - dotfiles
