---

- name: install packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - device-mapper-persistent-data
    - lvm2

- name: add yum repository
  become: yes
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker
  become: yes
  yum:
    name: docker-ce
    state: present

- name: add user to docker group
  become: yes
  shell: usermod -aG docker "{{ ansible_user_id }}"

- name: start docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
