---

- name: install packages
  become: yes
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - linux-image-extra-{{ ansible_kernel }}
      - linux-image-extra-virtual
  when: ansible_distribution_release == "trusty"
  tags:
    - docker

- name: add apt key
  become: yes
  shell: apt-key adv --fetch-keys=https://download.docker.com/linux/ubuntu/gpg
  tags:
    - docker

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present
  tags:
    - docker

- name: install docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - docker

- name: add user to docker group
  become: yes
  shell: usermod -aG docker "{{ ansible_user_id }}"
  tags:
    - docker

- name: start docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker
