---

- name: add apt key
  become: yes
  shell: curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
  tags:
    - code

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present
  tags:
    - code

- name: install code
  become: yes
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - code
  tags:
    - code
