---

- name: set timezone
  become: yes
  timezone:
    name: Asia/Tokyo

- name: add yum repository
  become: yes
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: install packages
  become: yes
  yum:
    name: yum-utils
    state: present
