---

- name: install tk-dev
  become: yes
  apt:
    name: tk-dev
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: install pyenv
  shell: |
    eval "$(anyenv init -)"
    anyenv install -s pyenv
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"

- name: install python
  shell: |
    eval "$(anyenv init -)"
    pyenv install -s {{ python_version }}
    pyenv global {{ python_version }}
    pip install pipenv
  environment:
    CONFIGURE_OPTS: --enable-shared
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"
