---

- name: add apt key
  become: yes
  shell: apt-key adv --fetch-keys=https://apt.llvm.org/llvm-snapshot.gpg.key
  tags:
    - llvm

- name: add repository
  become: yes
  apt_repository:
    repo: "deb http://apt.llvm.org/{{ ansible_distribution_release }}/ llvm-toolchain-{{ ansible_distribution_release }} main"
    filename: llvm
    state: present
  tags:
    - llvm

- name: install packages
  become: yes
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - clang
      - clang-format
      - libclang-dev
      - lldb
      - llvm-dev
  tags:
    - llvm
