---

- name: download
  become: yes
  unarchive:
    src: https://github.com/docopt/docopt.cpp/archive/v{{ docopt_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
    creates: /usr/local/src/docopt.cpp-{{ docopt_version }}

- name: compile and install
  become: yes
  shell: "{{ item }}"
  with_items:
    - cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/local/bin/ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/stow/docopt-{{ docopt_version }} -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DUSE_BOOST_REGEX=1 .
    - ninja install
  args:
    chdir: /usr/local/src/docopt.cpp-{{ docopt_version }}
    warn: no
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: stow
  become: yes
  shell: stow -R docopt-{{ docopt_version }}
  args:
    chdir: /usr/local/stow
