---

- name: add apt repository
  become: yes
  apt_repository:
    repo: 'ppa:git-core/ppa'
  tags:
    - scm

- name: install packages
  become: yes
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - git
      - openssh-client
      - procps
  tags:
    - scm

- name: install git-lfs
  become: yes
  shell: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
  args:
    warn: no
  tags:
    - scm
