---

- name: install packages
  become: yes
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - autoconf
      - automake
      - bzip2
      - dpkg-dev
      - file
      - g++
      - gcc
      - imagemagick
      - libbz2-dev
      - libc6-dev
      - libcurl4-openssl-dev
      - libdb-dev
      - libevent-dev
      - libffi-dev
      - libgdbm-dev
      - libgeoip-dev
      - libglib2.0-dev
      - libgmp-dev
      - libjpeg-dev
      - libkrb5-dev
      - liblzma-dev
      - libmagickcore-dev
      - libmagickwand-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libpng-dev
      - libpq-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libwebp-dev
      - libxml2-dev
      - libxslt-dev
      - libyaml-dev
      - make
      - patch
      - unzip
      - xz-utils
      - zlib1g-dev
      - libmysqlclient-dev
  tags:
    - buildpack

- name: install packages
  become: yes
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - libtool-bin
  when: ansible_distribution_major_version|int >= 16
  tags:
    - buildpack
