---

- name: install corretto
  become: yes
  yum:
    state: present
    name:
      - "{{ rpm }}"
  tags:
    - java

- name: install jenv
  shell: |
    eval "$(anyenv init -)"
    anyenv install -s jenv
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"
  tags:
    - java

- name: enable java
  shell: |
    eval "$(anyenv init -)"
    jenv add {{ java_home }}
    jenv global {{ java_version }}
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"
  tags:
    - java
