---

- name: install guake
  become: yes
  yum:
    state: present
    name:
      - guake
  tags:
    - guake

- name: enable auto start
  become: yes
  copy:
    src: /usr/share/applications/guake.desktop
    dest: /etc/xdg/autostart/guake.desktop
    remote_src: yes
  tags:
    - guake
