---

- name: install nodenv
  shell: |
    eval "$(anyenv init -)"
    anyenv install -s nodenv
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"
  tags:
    - node

- name: install node
  shell: |
    eval "$(anyenv init -)"
    nodenv install -s {{ node_version }}
    nodenv global {{ node_version }}
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"
  tags:
    - node
