---

- name: add rpm key
  become: yes
  rpm_key:
    key: https://pkg.osquery.io/rpm/GPG
    state: present

- name: add yum repository
  become: yes
  shell: yum-config-manager --add-repo https://pkg.osquery.io/rpm/osquery-s3-rpm.repo

- name: install osquery
  become: yes
  yum:
    name: osquery
    state: present
