---

- name: add apt key
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B

- name: add apt respository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://pkg.osquery.io/deb deb main
    filename: osquery
    state: present

- name: install osquery
  become: yes
  apt:
    name: osquery
    state: present
    update_cache: yes
    cache_valid_time: 3600
